# whether to enable project activation/switching between the projects defined below using the
# "activate_project" command. If this is enabled, you can instruct the agent to switch to a project
# by its name (see "projects" below).
# Note that if this is enabled, then per-project tool activation will be handled within Serena,
# i.e. Serena will provide all tools but will disallow the execution of tools that are not enabled for
# the current project. This is because clients typically do not respond to a changed set of tools.
enable_project_activation: True

# Add your list of projects here (which you can switch between using "activate_project").
# Every list item must be a path to the project's root directory (e.g. "/path/to/myproject"), with the
# configuration file being located in "/path/to/myproject/.serena/project.yml", or a dict mapping
# project_name to project_path (to avoid name collisions).
# You can activate a project by its name using the "activate_project" command.
# If the name is not explicitly set, the name of the project will be the name of the directory 
# ("myproject" in the example above).
# Note: comments in the block below are not preserved when saving the config file,
# so we recommend to not have any comments directly below the "projects" key.
projects:
  - /path/to/myproject
  - project_name: /path/to/myproject


gui_log_window: False
# Whether to open a graphical window with Serena's logs (not supported on macOS).
# This is useful both for troubleshooting and for monitoring the tool calls,
# especially when using the agno playground, since the tool calls are not always shown,
# and the input params are never shown in the agno UI.
# When used as MCP server for Claude Desktop, the logs are primarily for troubleshooting.
# Note: unfortunately, the various entities starting the Serena server or agent do so in
# mysterious ways, often starting multiple instances of the process without shutting down
# previous instances. This leads to multiple log windows being opened, and only the last
# window being updated. Since we can't control how agno or Claude Desktop start Serena,
# we have to live with this limitation for now.
#
# Limitations: doesn't seem to work with the community version of Claude Desktop for Linux
# Might also cause problems with some MCP clients - if you have any issues, try disabling this

gui_log_level: 20
# minimum log level for the GUI log window (10 = debug, 20 = info, 30 = warning, 40 = error)
