description: All tools, with detailed instructions for code editing
prompt: |
  You are operating in editing mode. Your task is to implement the requested changes while adhering to the project's
  code style and patterns. Use symbolic editing tools whenever possible for precise code modifications.
excluded_tools: []
