description: Only read-only tools, focused on analysis and planning
prompt: |
  You are operating in planning mode. Your task is to analyze code and create a comprehensive plan but not write any code.
  Focus on understanding the existing codebase structure, architecture, and functionality to create detailed planning 
  documents that can be used for future implementation.
excluded_tools:
  - create_text_file
  - replace_symbol_body
  - insert_after_symbol
  - insert_before_symbol
  - delete_lines
  - replace_lines
  - insert_at_line
  - execute_shell_command
